### ISSUE TITLE
Cosign doesn't accept Digicert's TSA certificate when verifying a signature

### ISSUE THREAD

**Issue by alt-enio** [sigstore/cosign#3632]
**Description**

I signed an image including a timestamp from Digicert (using http://timestamp.digicert.com).

To verify that signature I had to get the TSA certificate that they publish. For example here (https://knowledge.digicert.com/general-information/rfc3161-compliant-time-stamp-authority-server).  Cosign requires the full certificate chain and here lies the problem.

When building the chain from the certificates provided by Digicert on that page I got the following error:
`Error: no matching signatures: unable to verify RFC3161 timestamp bundle: no TSA root certificate(s) provided to verify timestamp`.

It appears that Digicert's Root certificate is not root enough for cosign. After debugging a bit I got to function `SplitPEMCertificateChain` (utils.go) which only considers that a certificate is root if it's self-signed. This is not the case for Digicert. There is a more general certificate used to sign that alleged Root certificate. Not sure if the criteria should be revised.

In Digicert's case, "Digicert Trusted Root G4" certificate is signed by "DigiCert Assured ID Root CA".

So, I included the true Root certificate in the chain.

Consequently, I got the following error:
`Error: no matching signatures: unable to verify RFC3161 timestamp bundle: failed to verify EKU on leaf certificate: failed to verify EKU on intermediate certificate: certificate has 0 extended key usages, expected only one`.

More debugging. I got to function `verifyLeafAndIntermediatesTimestampingEKU` (...go\pkg\mod\github.com\sigstore\timestamp-authority@v1.2.2\pkg\verification\verify.go) which has this comment: "_Verify the leaf and intermediate certificates (called "EKU chaining") all have the extended key usage set to only time stamping usage_". So, the intermediate certificates have to be set exclusively for timestamping usage. This was no longer the case with my chain because Digicert's Trusted Root G4, now turned intermediate, has more uses. Is it reasonable to require **all** intermediates to be set exclusively for timestamping?

So, it appears, for now, that Digicert's TSA can't be used for signing.

In my opinion, this could be fixed in one of two ways:
  * review the criteria for what is a root certificate
  * relax the exclusivity of timestamping use in intermediate certificates, especially if they are deep in the chain (IMO, this solution is more reasonable).

**Comment by haydentherapper** [comment]
Hey, this is a great question. There's a few issues at play here:

1. We don't have a great UI around providing trusted roots (which could be self-signed "roots" or intermediates, up to the client) and chain builders (always intermediates). Right now, for timestamping, we are automatically assuming that self-signed == root.
2. Digicert is treating what we are currently calling an intermediate as a root, which is why they have no technical constraints on Digicert Trusted Root G4
3. We are following the CAB Forum's Server Cert baseline requirements for Subordinate CA Technical Constraints, even though we're private PKI

To approach each of these issues, we could:

1. Fix the UI. We've discussed this in another issue. A long-term goal is to allow users to specify a [trust root](https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_trustroot.proto) and to allow the trust root to contain [CA pools](https://github.com/sigstore/protobuf-specs/issues/249). This would let you specify the "Digicert Trusted Root G4" as the root.
2. No solution here under our control. I might argue that Digicert is not following best practices by issuing a root-like CA certificate off its root "DigiCert Assured ID Root CA". Also it's weird that "DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA" expires after "Digicert Trusted Root G4"...
3. Relax the constraint like you said. We are private PKI so we don't have to follow any baseline requirements. I would still enforce the end-entity issuing CA be constrained.

Lemme think on this.

> because Digicert's Trusted Root G4, now turned intermediate, has more uses. Is it reasonable to require all intermediates to be set exclusively for timestamping?

Actually, it looks like Trusted Root G4 has no extended key usages. I only see key usages "Digital Signature, Certificate Sign, CRL Sign". So the reason it's failing is because there are no extended key usages. You are right though that we are being too strict and should allow any additional extended key usages, but given that's not the issue here, I'll hold off on relaxing this constraint because I've only seen timestamping intermediates with exactly one EKU.

**Comment by chizou** [comment]
@haydentherapper , I reached out to my reps at DigiCert to get their response on this. Please don't shoot the messenger. Here's what they had to say....

> Summary
> The CoSign tool is not currently following the standards.  CoSign  would need to update the chain checking to handle more complex use cases. Our primary timestamp service is returning a chain that includes a cross signed intermediate to provide backward compatibility for older clients and at the same time supporting newer clients.  Sectigo would be an example of another timestamp service that does the same thing.
>  
>  
> Details
> From our Architect:
>  it seems there are some misunderstandings on the problem with regards to the standards:

> •	**Cross-Certified certificates**: This seems to be a confusing point due to the fact that the Common Name of the intermediate would have the word "Root" in it. Since it is cross-certified, the intermediate will have the same Subject DN and public key as the root being cross-certified but the IssuerDN will have the name of the new issuer. This is the standard way to provide multiples path to different trust anchors so that the service checking the chain can have a different set of anchors than another service doing the same check. This allows for EE certs (in this case the timestamp signer) to chain to both and older and newer roots and thus support older and newer clients at the same time. In this case the anchor could be found any different parts of the provided chain and not always at the end. Sectigo's TSA is another example of this approach.
> •	**From the bug: "We are following the CAB Forum's Server Cert baseline requirements for Subordinate CA Technical Constraints, even though we're private PKI"**. This is not fully accurate as section 7.1.2.2.3 Cross-Certified Subordinate CA Extensions of the baseline requirements allows for Unrestricted EKU's in cross-certified intermediates. That means the EKU extension can be omitted for for these types of intermediates. See chain checking below.
> •	**From the bug: "Relax the constraint like you said. We are private PKI so we don't have to follow any baseline requirements. I would still enforce the end-entity issuing CA be constrained"**. As previously mentioned, the baseline requirements do not require cross-certified intermediates (and roots) to have the EKU extension. The EE timestamp signer and all other intermediates must have the Timestamp OID in the EKU.  After that, standard EKU chain checking from RFC 5280 is performed.  The EKU check passes IF the certificate being examined in the chain has the Timestamp OID or the EKU has the anyExtendedKeyUsage OID or the EKU extension is not present (which implies all usages are allowed).
> •	**From the bug: "Also it's weird that "DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA" expires after "Digicert Trusted Root G4".** It is normal for cross-certified intermediates to have dates in which one will expire before something above it in the chain. When checking the validity of an certificate in the chain, RFC 5280 only requires each certificate to be individually valid at the moment the chain is being check and it does not require any certs in the chain to expire before others do.

**Comment by mktgbnk** [comment]
Was there any progress or workaround on this? We are experiencing the same issue when using internal cert issuer.

**Comment by mktgbnk** [comment]
I can look into it, please confirm my understanding:
- keep leaf certificate as is, with strict check
- keep "what is root" as is
- relax intermediate cert check, where if no EKU extension is present (means allow all) or timestamp EKU is present we allow that

**Comment by Hayden-IO** [comment]
Mentioned on the PR, but I'd like to still enforce that the intermediate that issued the leaf certificate has an EKU of Timestamping, which should work when verifying the Digicert chain as `DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA` sets the EKU to be Timestamping. We should relax the EKU check for all other intermediates as you've already implemented.

Longer-term, we will change this so that clients can choose the root of trust, but for now, including `DigiCert Assured ID Root CA` should be a sufficient mitigation once we've merged [sigstore/timestamp-authority#1078](https://github.com/sigstore/timestamp-authority/pull/1078) and updated Cosign.

**Comment by Hayden-IO** [comment]
https://github.com/sigstore/timestamp-authority/releases/tag/v1.2.8 has been released which includes the relaxed intermediate validation. Just need to update Cosign to use v1.2.8.

**Comment by mbharambe1** [comment]
@haydentherapper 
Hi, when is the next release?

**Comment by mbharambe1** [comment]
@haydentherapper @mktgbnk 
I tried to use the change from the main but it fails 
```
 $(go env GOPATH)/bin/cosign verify --key <public-key> --use-signed-timestamps --timestamp-certificate-chain=digicert_tsa_chain.pem <image>

Error: unable to load TSA certificates: TSA certificate chain must contain at least one root certificate
error during command execution: unable to load TSA certificates: TSA certificate chain must contain at least one root certificate
```

digicert_tsa_chain.pem has all 3 certs from https://knowledge.digicert.com/general-information/rfc3161-compliant-time-stamp-authority-server

**Comment by mbharambe1** [comment]
I added DigiCert Assured ID Root CA to the certificate chain. Now I am getting 

```
Error: no matching signatures: unable to verify RFC3161 timestamp bundle: failed to verify TSA certificate: certificate embedded in the TSR does not match the provided TSA certificate
error during command execution: no matching signatures: unable to verify RFC3161 timestamp bundle: failed to verify TSA certificate: certificate embedded in the TSR does not match the provided TSA certificate
```

I tried with Digicert Trusted Root G4, DigiCert Assured ID Root CA in the chain. cosign verify still fails with the above issue. 

Please provide details on what is required in the certificate chain. @haydentherapper @mktgbnk

**Comment by Hayden-IO** [comment]
Will need to investigate more. Can you confirm the ordering of the chain and the command you used?

**Comment by mbharambe1** [comment]
I used
```
cat TSACertificate.cer \
    DigiCertTrustedG4RSA4096SHA256TimeStampingCA.cer \
    DigiCertTrustedRootG4.cer \
    DigiCertAssuredIDRootCA.crt.pem \
    > digicert_assured_tsa_chain.pem
```
Also if I run with a certificate I get the following error:

```
$(go env GOPATH)/bin/cosign verify --insecure-ignore-tlog=true --certificate <> --certificate-identity-regexp '.*' --certificate-oidc-issuer-regexp '.*'  --insecure-ignore-sct <image>  --use-signed-timestamps --timestamp-certificate-chain=digicert_assured_tsa_chain.pem --verbose

WARNING: Skipping tlog verification is an insecure practice that lacks transparency and auditability verification for the signature.
Error: cert verification failed: x509: certificate signed by unknown authority. Check your TUF root (see cosign initialize) or set a custom root with env var SIGSTORE_ROOT_FILE
error during command execution: cert verification failed: x509: certificate signed by unknown authority. Check your TUF root (see cosign initialize) or set a custom root with env var SIGSTORE_ROOT_FILE`
```

Tried to set SIGSTORE_ROOT_FILE to DigiCertTrustedRootG4.cer but still same issue as above.

**Comment by mbharambe1** [comment]
@haydentherapper @mktgbnk Can you provide guidance on how to verify a signature using timestamps? I tried 
 a self-signed CA + code signing cert for testing the fix, but I am still getting a certificate signed by an unknown authority

```
$(go env GOPATH)/bin/cosign verify --insecure-ignore-tlog=true --certificate server.crt --insecure-ignore-sct  <IMAGE> --use-signed-timestamps --timestamp-certificate-chain=/home/worker/digicert_assured_tsa_chain.pem --verbose --certificate-identity-regexp '.*' --certificate-oidc-issuer-regexp '.*' --offline
WARNING: Skipping tlog verification is an insecure practice that lacks transparency and auditability verification for the signature.
Error: cert verification failed: x509: certificate signed by unknown authority. Check your TUF root (see cosign initialize) or set a custom root with env var SIGSTORE_ROOT_FILE
error during command execution: cert verification failed: x509: certificate signed by unknown authority. Check your TUF root (see cosign initialize) or set a custom root with env var SIGSTORE_ROOT_FILE

```

I made sure that both server.crt and ca.crt have X509v3 Subject Alternative Names

**Comment by asbrboac** [comment]
Hello @mbharambe1, @haydentherapper 

I suspect what might be the root cause is that the chain that @mbharambe1 is supplying to `cosign` for the TSA validation likely is not the one which is being used by DigiCert anymore.

As of a few weeks ago, the leaf signing certificate from the TSA appears to no longer be the one from [the DigiCert site](https://knowledge.digicert.com/general-information/rfc3161-compliant-time-stamp-authority-server), but rather looks to be the following:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0b:ae:66:bc:5a:ba:7f:95:87:c6:f9:e9:04:e3:33:04
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = "DigiCert, Inc.", CN = DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA
        Validity
            Not Before: Sep 26 00:00:00 2024 GMT
            Not After : Nov 25 23:59:59 2035 GMT
        Subject: C = US, O = DigiCert, CN = DigiCert Timestamp 2024
```

I assume that this is because of an expected leaf rotation.

To show that the workaround for this issue is working, an example is shown below.

I can create the TSA chain by pulling out the certificate chain except for the root **already present in the TSA's reply**, then check that it's rooted in the tsa root expected, and then concatenate those to be fed to `cosign` -- for example via the following in bash (pseudocode):

```bash
set -e

# download the signature
cosign download signature <image> > signature.json

# extract SignedRFC3161Timestamp 
jq -r .RFC3161Timestamp.SignedRFC3161Timestamp signature.json | base64 -d > tsa.der

# extract the TSA chain that's present in the RFC Timestamp
openssl ts -reply -in tsa.der -token_out | openssl pkcs7 -inform DER -print_certs > extracted_tsa.pem

# Validate that the chain supplied is indeed rooted in the expected TSA trust root
# Do not go forward with the cosign call unless it has been shown that the chain provided
# in the signature json is rooted in something that the system trusts
openssl verify <...> -CAfile tsa_root.pem -untrusted extracted_tsa.pem <...>

# if so, then concatenate the expected Root CA from the TSA
cat extracted_tsa.pem tsa_root.pem > extracted_tsa_with_root.pem

# verify
cosign verify <...> --use-signed-timestamps --timestamp-certificate-chain extracted_tsa_with_root.pem <image>

```

In this case, `tsa_root.pem` would be the Digicert Assured ID Root CA, as was described as the workaround to relax constraints on the EKU in #4219. 

With this, **validation in cosign works correctly**. For this reason, I would argue that this issue should be closed -- the workaround does work if supplied with the correct chain (though there end up being a few steps to get that chain). Hopefully then the EKU relaxation which was already merged could make its way into a release.

@haydentherapper, this makes me wonder why the full chain including leaf, all intermediates, and root need to be supplied to `cosign` considering that everything except the root would appear to exist already in the reply from the time stamping authority. 

Since leaves and intermediates are expected to change at a higher frequency than roots, and everything except the root is already present in the TSA reply, couldn't the user _only supply the root(s)_, and the chain from leaf to final intermediate is pulled out of the TSA by `cosign`, which can read the lower parts of the chain directly from the TSA reply in the signature json (instead of having the client pull it out from the signature json) and then validate that they are indeed rooted in the root CA that the client wants to validate against? 

In this way, clients would not need to include whole chains when leaves or intermediates rotate, which happens rather often; `cosign` would still need to ensure that the chain presented is rooted in a root supplied by the client. I don't think that is the same issue as this particular one, but perhaps an enhancement?

**Comment by asbrboac** [comment]
@alt-enio, @haydentherapper, @mktgbnk - Please see my prior comment. I believe that the fix / workaround that was already done works and that it likely could be closed (in case it was reopened due to @mbharambe1 's finding).

I believe the root cause of @mbharambe1 's finding was related to DigiCert rotating their leaf, which also now appears to be available on their [website](https://knowledge.digicert.com/general-information/rfc3161-compliant-time-stamp-authority-server) in the meantime.

If you agree, do you feel this could be considered closed?

Note: edit -- I see that this functionality works in the newer release of v2.5.2! Thanks!
